version: '3.4'

services:

  azure.cosmosdb:
    image: mcr.microsoft.com/cosmosdb/linux/azure-cosmos-emulator
    container_name: azure.cosmosdb
    environment:
       - AZURE_COSMOS_EMULATOR_PARTITION_COUNT=5 
       - AZURE_COSMOS_EMULATOR_ENABLE_DATA_PERSISTENCE=true
       - AZURE_COSMOS_EMULATOR_IP_ADDRESS_OVERRIDE=172.26.176.1
    ports:
       - 8081:8081 
       - 10251:10251 
       - 10252:10252 
       - 10253:10253 
       - 10254:10254
  azure.eventGrid:
    image: pmcilreavy/azureeventgridsimulator:latest
    container_name: azure.eventGrid
    volumes:
      - ./docker:/aegs:ro
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_Kestrel__Certificates__Default__Path=/aegs/azureEventGridSimulator.pfx
      - ASPNETCORE_Kestrel__Certificates__Default__Password=Y0urSup3rCrypt1cPa55w0rd!
      - AEGS_Topics__0__name=HouseTopic
      - AEGS_Topics__0__port=60101
      - AEGS_Topics__0__key=TheLocal+DevelopmentKey=
      - AEGS_Topics__0__subscribers__0__name=RequestCatcherSubscription
      - AEGS_Topics__0__subscribers__0__endpoint=https://azureeventgridsimulator.requestcatcher.com/
      - AEGS_Topics__0__subscribers__0__disableValidation=true
      - AEGS_Topics__0__subscribers__1__name=AzureFunctionSubscription
      - AEGS_Topics__0__subscribers__1__endpoint=http://host.docker.internal:7127/runtime/webhooks/EventGrid?functionName=UpdateExpensesOnHouseUpdate
      - AEGS_Topics__0__subscribers__1__disableValidation=true
    ports:
      - "60101:60101"
volumes:
  docker: