name: Build & Deploy UI

on:
  workflow_dispatch:
  push:
    branches:
    - master
    paths:
    - 'ui/**'
defaults:
 run:
  working-directory: ./ui
jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v3
    
    - name: Install Node.js
      uses: actions/setup-node@v1
      with:
        node-version: 13.x
    
    - name: Install NPM packages
      run: npm ci
    
    - name: Build project assets
      run: npm run build
    
    - name: Upload production-ready build files
      uses: actions/upload-artifact@v3
      with:
        name: ui-prod-files
        path: ./ui/webpack/build
  
  deploy:
    name: Deploy
    needs: build
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/master'
    
    steps:
    - name: Download artifact
      uses: actions/download-artifact@v3
      with:
        name: ui-prod-files

    - name: Deploy to gh-pages
      uses: peaceiris/actions-gh-pages@v3
      if: ${{ github.ref == 'refs/heads/master' }}
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./out